### ISSUE TITLE
Installing nefis fails.

### ISSUE THREAD

**Issue by SiggyF** [openearth/nefis-python#4]
* Nefis version: 0.2.1
* Python version: 3.6
* Operating System: Debian

### Description

The installation of nefis from pypi fails. 

### What I Did

```
pip install nefis
```
This gives the following error:

```
Downloading nefis-0.2.1.zip (118kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0t88m6o3/nefis/setup.py", line 49, in <module>
        for fileName in os.listdir(os.path.join(".", "data")):
    FileNotFoundError: [Errno 2] No such file or directory: './data'
```

**Comment by yahiakala** [comment]
I believe the PyPI version only works with Python 2.7. They haven't updated it since 2015.
